import { Canvas, useFrame } from '@react-three/fiber'
import { Bloom, EffectComposer, Vignette } from '@react-three/postprocessing'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import * as THREE from 'three'
import { GameShell, type GameResult } from '../GameShell'
import { useSystem } from '../../state/system'
import { sfx } from '../../audio/engine'
import { formatScore, labelTexture } from '../../lib/utils'
import HoloGrid from '../../world/fx/HoloGrid'
import ParticleField from '../../world/fx/Particles'

interface Pairing { id: string; symptom: string; cause: string; color: string }
const PAIRS: Pairing[] = [
  { id: 'oom', symptom: '502 after deploy', cause: 'memory limit too low', color: '#ff5a3c' },
  { id: 'probe', symptom: 'rollout never completes', cause: 'readiness probe wrong', color: '#5ce1ff' },
  { id: 'lag', symptom: 'consumer lag climbing', cause: 'partition count too low', color: '#ffb545' },
  { id: 'cert', symptom: 'TLS handshake fails', cause: 'certificate expired', color: '#a682ff' },
  { id: 'dns', symptom: 'intermittent timeouts', cause: 'DNS cache TTL', color: '#4dffa0' },
  { id: 'quota', symptom: 'pods stuck pending', cause: 'namespace quota hit', color: '#ff7fb0' },
]
interface Tile { key: string; pairId: string; text: string; role: 'symptom' | 'cause'; color: string; x: number; y: number; revealed: boolean; matched: boolean; wrong: number }
const COLS = 4, ROWS = 3, TIME_LIMIT = 80
function buildTiles(): Tile[] {
  const entries = PAIRS.flatMap((p) => [{ pairId: p.id, text: p.symptom, role: 'symptom' as const, color: p.color }, { pairId: p.id, text: p.cause, role: 'cause' as const, color: p.color }])
  const shuffled = entries.sort(() => Math.random() - 0.5)
  return shuffled.map((e, i) => ({ key: `${e.pairId}-${e.role}`, ...e, x: ((i % COLS) - (COLS - 1) / 2) * 2.45, y: -(Math.floor(i / COLS) - (ROWS - 1) / 2) * 1.75, revealed: false, matched: false, wrong: 0 }))
}
function TileMesh({ tile, onFlip, index }: { tile: Tile; onFlip: (i: number) => void; index: number }) {
  const group = useRef<THREE.Group>(null)
  const front = useMemo(() => labelTexture(tile.text.toUpperCase(), { color: tile.color, size: 40, weight: 700, letterSpacing: 1 }), [tile.text, tile.color])
  const roleTex = useMemo(() => labelTexture(tile.role === 'symptom' ? 'SYMPTOM' : 'CAUSE', { color: '#7d919b', size: 26, weight: 800, letterSpacing: 3 }), [tile.role])
  useFrame((state, dt) => { const g = group.current; if (!g) return; const open = tile.revealed || tile.matched; g.rotation.y = THREE.MathUtils.damp(g.rotation.y, open ? 0 : Math.PI, 8, dt); const bob = tile.matched ? Math.sin(state.clock.elapsedTime * 2 + index) * 0.06 : 0; g.position.y = THREE.MathUtils.damp(g.position.y, tile.y + bob, 6, dt); g.scale.setScalar(THREE.MathUtils.damp(g.scale.x, tile.matched ? 0.94 : 1, 6, dt)) })
  return <group ref={group} position={[tile.x, tile.y, 0]}><mesh onClick={(e) => { e.stopPropagation(); onFlip(index) }} onPointerOver={(e) => { e.stopPropagation(); if (!tile.matched) document.body.style.cursor = 'pointer' }} onPointerOut={() => { document.body.style.cursor = 'default' }}><boxGeometry args={[2.2, 1.5, 0.1]} /><meshStandardMaterial color={tile.matched ? '#0d2b21' : '#0d151a'} metalness={0.8} roughness={0.3} emissive={tile.matched ? '#1f8f5f' : tile.revealed ? tile.color : '#0e2733'} emissiveIntensity={tile.matched ? 1.5 : tile.revealed ? 0.7 : 0.35} /></mesh><mesh position={[0, 0.18, 0.056]}><planeGeometry args={[1.9, (1.9 * (front.image as HTMLCanvasElement).height) / (front.image as HTMLCanvasElement).width]} /><meshBasicMaterial map={front} transparent depthWrite={false} toneMapped={false} /></mesh><mesh position={[0, -0.42, 0.056]}><planeGeometry args={[0.85, (0.85 * (roleTex.image as HTMLCanvasElement).height) / (roleTex.image as HTMLCanvasElement).width]} /><meshBasicMaterial map={roleTex} transparent depthWrite={false} toneMapped={false} /></mesh><mesh position={[0, 0, -0.056]} rotation={[0, Math.PI, 0]}><planeGeometry args={[2.1, 1.4]} /><meshBasicMaterial color="#0b2733" transparent opacity={0.9} toneMapped={false} /></mesh><mesh position={[0, 0, -0.062]} rotation={[0, Math.PI, 0]}><torusGeometry args={[0.34, 0.03, 6, 20]} /><meshBasicMaterial color="#1c5568" toneMapped={false} /></mesh></group>
}
function Board({ tiles, onFlip }: { tiles: Tile[]; onFlip: (i: number) => void }) { return <><ambientLight intensity={0.35} /><pointLight position={[0, 3, 7]} intensity={30} distance={26} color="#a682ff" /><pointLight position={[-6, -2, 5]} intensity={14} distance={20} color="#5ce1ff" /><fog attach="fog" args={['#05060c', 12, 32]} /><HoloGrid position={[0, -4.4, -3]} size={50} color="#1b1030" accent="#a682ff" scale={20} wave={0.25} segments={48} /><ParticleField count={180} spread={20} colorA="#a682ff" colorB="#5ce1ff" rise={0.24} size={2} opacity={0.55} position={[0, 0, -2]} seed={5} />{tiles.map((t, i) => <TileMesh key={t.key} tile={t} index={i} onFlip={onFlip} />)}</> }
export default function RootCauseMatrix() {
  const quality = useSystem((s) => s.quality), unlock = useSystem((s) => s.unlock)
  const [tiles, setTiles] = useState<Tile[]>(() => buildTiles()), [time, setTime] = useState(TIME_LIMIT), [flips, setFlips] = useState(0), [wrong, setWrong] = useState(0), [result, setResult] = useState<GameResult | null>(null), [started, setStarted] = useState(false), [paused, setPaused] = useState(false)
  const lock = useRef(false), timeRef = useRef(TIME_LIMIT), wrongRef = useRef(0), flipRef = useRef(0); timeRef.current = time; wrongRef.current = wrong; flipRef.current = flips
  const matched = tiles.filter((t) => t.matched).length / 2, matchedRef = useRef(0); matchedRef.current = matched
  const finish = useCallback((won: boolean, pairsMatched: number) => { if (won) unlock('matrix-clear'); const remaining = Math.max(0, timeRef.current), wrongCount = wrongRef.current; const score = won ? Math.round(remaining * 14 + 360 - wrongCount * 25) : Math.round(pairsMatched * 90); setResult({ score: Math.max(0, score), verdict: won ? (remaining > 45 ? 'Correlated instantly.' : 'Root cause found.') : 'Window closed.', lines: [{ label: 'Pairs matched', value: `${pairsMatched} / 6` }, { label: 'Time left', value: `${remaining.toFixed(0)}s` }, { label: 'Wrong correlations', value: String(wrongCount) }, { label: 'Nodes opened', value: String(flipRef.current) }] }) }, [unlock])
  const start = useCallback(() => { setTiles(buildTiles()); setTime(TIME_LIMIT); timeRef.current = TIME_LIMIT; setFlips(0); setWrong(0); setResult(null); setStarted(true); setPaused(false); lock.current = false }, [])
  const flip = useCallback((index: number) => { if (lock.current || !started || result || paused) return; setTiles((prev) => { const t = prev[index]; if (!t || t.matched || t.revealed) return prev; const open = prev.filter((x) => x.revealed && !x.matched); if (open.length >= 2) return prev; sfx('click'); const next = prev.map((x, i) => (i === index ? { ...x, revealed: true } : x)); setFlips((f) => f + 1); const nowOpen = next.filter((x) => x.revealed && !x.matched); if (nowOpen.length === 2) { const [a, b] = nowOpen, isMatch = a.pairId === b.pairId && a.role !== b.role; lock.current = true; window.setTimeout(() => { setTiles((cur) => { const resolved = cur.map((x) => x.revealed && !x.matched ? isMatch ? { ...x, matched: true, revealed: true } : { ...x, revealed: false, wrong: x.wrong + 1 } : x); if (resolved.every((x) => x.matched)) window.setTimeout(() => finish(true, 6), 0); return resolved }); lock.current = false }, isMatch ? 320 : 780); if (isMatch) sfx('confirm'); else { sfx('deny'); setWrong((w) => w + 1) } } return next }) }, [started, result, paused, finish])
  useEffect(() => { if (!started || result || paused) return; const id = window.setInterval(() => { const next = timeRef.current - 0.1; if (next <= 0) { window.clearInterval(id); timeRef.current = 0; setTime(0); finish(false, matchedRef.current); return } setTime(next) }, 100); return () => window.clearInterval(id) }, [started, result, paused, finish])
  const hud = useMemo(() => <div className="matrix-hud"><div className="term-metric"><b className={time < 15 ? 'critical' : ''}>{time.toFixed(0)}s</b><small>WINDOW</small></div><div className="term-metric"><b>{matched}/6</b><small>CORRELATED</small></div><div className="term-metric"><b>{formatScore(wrong)}</b><small>WRONG</small></div></div>, [time, matched, wrong])
  return <GameShell id="matrix" hud={started ? hud : null} result={result} onRestart={start} paused={paused} onTogglePause={() => setPaused((p) => !p)}><Canvas dpr={quality === 'low' ? [0.7, 1] : [1, 1.6]} gl={{ antialias: quality === 'ultra', powerPreference: 'high-performance' }} camera={{ fov: 46, position: [0, 0, 11], near: 0.1, far: 80 }} onCreated={({ gl }) => { gl.toneMapping = THREE.ACESFilmicToneMapping }}><color attach="background" args={['#05060c']} /><Board tiles={tiles} onFlip={flip} />{quality !== 'low' && <EffectComposer multisampling={0}><Bloom luminanceThreshold={0.5} mipmapBlur intensity={0.7} /><Vignette offset={0.2} darkness={0.55} eskil={false} /></EffectComposer>}</Canvas>{!started && !result && <div className="game-over"><div className="game-over-card"><span className="eyebrow" style={{ color: '#a682ff' }}>MEMORY · LOGIC</span><h2>Correlate the signal.</h2><p className="result-teach">Twelve nodes hide six symptoms and their six real causes. Open two at a time and pair them. These are actual failure modes — a 502 straight after a deploy really is usually a memory limit, and a rollout that never completes really is usually a bad readiness probe.</p><div className="result-actions"><button className="btn-primary" onClick={start}>OPEN THE MATRIX</button></div></div></div>}</GameShell>
}
