import { useFrame } from '@react-three/fiber'
import { useEffect, useMemo, useRef } from 'react'
import * as THREE from 'three'
import { useMission } from '../../state/mission'
import { useSystem } from '../../state/system'
import HoloGrid from '../fx/HoloGrid'
import ParticleField from '../fx/Particles'
import { DataStream, HoloPanel, Label3D, LightShaft } from '../fx/Primitives'

const GRID_X = 22
const GRID_Z = 16
const SPACING = 1.25

interface Tower { x:number; z:number; h:number; ns:0|1|2; phase:number }

function District() {
  const stage=useMission(s=>s.stage), mesh=useRef<THREE.InstancedMesh>(null), roofs=useRef<THREE.InstancedMesh>(null), heights=useRef<Float32Array>(new Float32Array(GRID_X*GRID_Z)), dummy=useMemo(()=>new THREE.Object3D(),[]), col=useMemo(()=>new THREE.Color(),[]), rolloutStart=useRef(0)
  const towers:Tower[]=useMemo(()=>{const list:Tower[]=[];for(let ix=0;ix<GRID_X;ix++){for(let iz=0;iz<GRID_Z;iz++){const i=ix*GRID_Z+iz,n=(Math.sin(i*12.9898)*43758.5453)%1,h=.55+Math.abs(n)*2.6,ns:0|1|2=ix<8?0:ix<15?1:2;list.push({x:(ix-(GRID_X-1)/2)*SPACING,z:(iz-(GRID_Z-1)/2)*SPACING,h,ns,phase:Math.abs(n)*6.28})}}return list},[])
  const rolling=stage==='cluster-rollout',incident=stage.startsWith('incident')&&stage!=='incident-recovered',recovered=stage==='incident-recovered'
  useEffect(()=>{if(rolling&&rolloutStart.current===0)rolloutStart.current=performance.now();if(!rolling&&!incident&&!recovered)rolloutStart.current=0},[rolling,incident,recovered])
  useFrame((state,dt)=>{const m=mesh.current,r=roofs.current;if(!m)return;const t=state.clock.elapsedTime,rolloutT=rolloutStart.current?(performance.now()-rolloutStart.current)/1000:0,front=-14+rolloutT*7.5;towers.forEach((tw,i)=>{let target=tw.h;if(tw.ns===1&&rolloutStart.current){const d=tw.x-front;if(d>0&&d<2.2)target=.1;else if(d<=0)target=tw.h*1.22}if(incident&&tw.ns===2)target=.18;if(recovered&&tw.ns===2)target=tw.h;const cur=heights.current[i]||tw.h,next=THREE.MathUtils.damp(cur,target,4.2,dt);heights.current[i]=next;dummy.position.set(tw.x,-2.4+next*.5,tw.z);dummy.scale.set(.78,next,.78);dummy.rotation.set(0,0,0);dummy.updateMatrix();m.setMatrixAt(i,dummy.matrix);if(r){dummy.position.set(tw.x,-2.4+next+.06,tw.z);dummy.scale.setScalar(next>.3?.16:.001);dummy.updateMatrix();r.setMatrixAt(i,dummy.matrix)}const pulse=.5+Math.sin(t*1.6+tw.phase)*.5;if(incident&&tw.ns===2)col.setHSL(.01,.95,.28+pulse*.24);else if(tw.ns===1&&rolloutStart.current&&tw.x-front<=0)col.setHSL(.4,.7,.24+pulse*.16);else if(tw.ns===0)col.setHSL(.53,.32,.11+pulse*.05);else if(tw.ns===1)col.setHSL(.5,.28,.13+pulse*.05);else col.setHSL(.08,.2,.11+pulse*.05);m.setColorAt(i,col);if(r){if(incident&&tw.ns===2)col.setHSL(.01,1,.5+pulse*.3);else col.setHSL(.45,.8,.4+pulse*.35);r.setColorAt(i,col)}});m.instanceMatrix.needsUpdate=true;if(m.instanceColor)m.instanceColor.needsUpdate=true;if(r){r.instanceMatrix.needsUpdate=true;if(r.instanceColor)r.instanceColor.needsUpdate=true}})
  return <><instancedMesh ref={mesh} args={[undefined,undefined,towers.length]} castShadow={false}><boxGeometry/><meshStandardMaterial metalness={.82} roughness={.34}/></instancedMesh><instancedMesh ref={roofs} args={[undefined,undefined,towers.length]}><sphereGeometry args={[1,6,6]}/><meshBasicMaterial toneMapped={false}/></instancedMesh></>
}

function ServiceRoads(){const lanes=useMemo(()=>[-4.6,0,4.6],[]);return <group position={[0,-2.42,0]}>{lanes.map(z=><mesh key={z} position={[0,0,z]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[GRID_X*SPACING+4,.34]}/><meshBasicMaterial color="#12414f" transparent opacity={.55} toneMapped={false}/></mesh>)}{[-5,0,5].map(x=><mesh key={x} position={[x,0,0]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[.28,GRID_Z*SPACING+4]}/><meshBasicMaterial color="#12414f" transparent opacity={.4} toneMapped={false}/></mesh>)}</group>}

export default function ClusterZone(){const stage=useMission(s=>s.stage),traffic=useMission(s=>s.trafficShift),quality=useSystem(s=>s.quality),active=stage.startsWith('cluster')||stage==='traffic-bridge'||stage.startsWith('incident'),incident=stage.startsWith('incident')&&stage!=='incident-recovered';if(!active)return null;const newFlow=Math.max(.08,traffic/100),oldFlow=Math.max(.08,1-traffic/100);return <group position={[0,0,-126]}><ambientLight intensity={.16}/><directionalLight position={[8,14,6]} intensity={1.5} color="#a8d8e6"/><pointLight position={[0,7,0]} intensity={10} distance={30} color={incident?'#ff5a3c':'#4dffa0'}/><pointLight position={[-11,3,6]} intensity={6} distance={18} color="#5ce1ff"/><HoloGrid position={[0,-2.46,0]} size={110} color="#07242e" accent={incident?'#ff5a3c':'#5ce1ff'} scale={38} pulse={incident?.55:.14} glitch={incident?.6:0} wave={.2}/><mesh position={[0,-2.5,0]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[46,40]}/><meshStandardMaterial color="#060a0c" metalness={.76} roughness={.52}/></mesh><ServiceRoads/><District/>{quality!=='low'&&<ParticleField count={300} spread={40} colorA="#5ce1ff" colorB="#4dffa0" rise={.22} size={2} opacity={.5} position={[0,3,0]} seed={53}/>} {[{x:-8.5,label:'NS · PLATFORM',color:'#5ce1ff'},{x:0,label:'NS · PAYMENTS',color:'#4dffa0'},{x:8.5,label:'NS · CUSTOMER',color:incident?'#ff5a3c':'#ffb545'}].map(d=><group key={d.label} position={[d.x,0,-11.5]}><LightShaft position={[0,2,0]} height={9} radiusTop={.15} radiusBottom={1.8} color={d.color} intensity={.55}/><Label3D text={d.label} position={[0,6.4,0]} height={.42} color={d.color} billboard/></group>)}<group position={[0,5.2,7.4]}><mesh scale={[19,.09,.09]}><boxGeometry/><meshStandardMaterial color="#1c5a68" emissive="#12414f" emissiveIntensity={1.4} metalness={.9} roughness={.3}/></mesh>{[-9.5,0,9.5].map(x=><mesh key={x} position={[x,-1.6,0]} scale={[.16,3.2,.16]}><boxGeometry/><meshStandardMaterial color="#16242a" metalness={.9} roughness={.35}/></mesh>)}<DataStream start={[-9.4,0,0]} end={[0,0,0]} count={16} speed={.09} flow={oldFlow} color="#8ea3ad" hotColor="#c9dbe2" radius={.06}/><DataStream start={[0,0,0]} end={[9.4,0,0]} count={16} speed={.14} flow={newFlow} color="#4dffa0" hotColor="#dfffee" radius={.06}/><Label3D text={`OLD ${100-traffic}%`} position={[-6.4,.7,0]} height={.34} color="#8ea3ad" billboard/><Label3D text={`NEW ${traffic}%`} position={[6.4,.7,0]} height={.34} color="#4dffa0" billboard/><HoloPanel position={[0,1.4,0]} size={[4.4,.9]} color="#5ce1ff" opacity={.3}/><Label3D text="TRAFFIC BRIDGE" position={[0,1.4,.02]} height={.28} color="#bfeaf7" billboard/></group><Label3D text="CLUSTER CITY" position={[0,9.4,-12]} height={.6} color="#7d8f97" billboard/></group>}
